# Generated by Django 4.1.4 on 2022-12-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_faculty_alter_department_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='img',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
