# Generated by Django 4.1.4 on 2022-12-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_alter_faculty_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
